/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GestionarVentas;

import utils.ButtonEditor;
import utils.ButtonRenderer;

/**
 *
 * @author rramirez
 */
public class DetalleVentaFrm extends javax.swing.JFrame {

    /**
     * Creates new form MenuFrm
     */
    public DetalleVentaFrm() {
        initComponents();
        setExtendedState(DetalleVentaFrm.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        configurarTabla();
    }

    public void configurarTabla() {
        SPVentas.getViewport().setBackground(java.awt.Color.WHITE);

        javax.swing.table.JTableHeader header = TblVentas.getTableHeader();
        header.setBackground(java.awt.Color.decode("#D2D2D2"));
        header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
        ((javax.swing.table.DefaultTableCellRenderer) header.getDefaultRenderer())
                .setHorizontalAlignment(javax.swing.JLabel.CENTER);
        header.setOpaque(false);

        javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        for (int i = 0; i < TblVentas.getColumnCount() - 1; i++)
        {
            TblVentas.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PnlHeader = new javax.swing.JPanel();
        PnlFooter = new javax.swing.JPanel();
        BtnBack = new javax.swing.JButton();
        PnlContenido = new javax.swing.JPanel();
        SPVentas = new javax.swing.JScrollPane();
        TblVentas = new javax.swing.JTable();
        PnlDetalleVenta = new javax.swing.JPanel();
        LblFolio = new javax.swing.JLabel();
        LblFecha = new javax.swing.JLabel();
        LblMetodo = new javax.swing.JLabel();
        LblEstado = new javax.swing.JLabel();
        LblTotoal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        PnlHeader.setBackground(new java.awt.Color(47, 102, 144));
        PnlHeader.setPreferredSize(new java.awt.Dimension(1024, 60));
        PnlHeader.setLayout(new java.awt.BorderLayout());
        getContentPane().add(PnlHeader, java.awt.BorderLayout.NORTH);

        PnlFooter.setBackground(new java.awt.Color(47, 102, 144));
        PnlFooter.setPreferredSize(new java.awt.Dimension(1024, 60));
        PnlFooter.setLayout(new java.awt.BorderLayout());

        BtnBack.setBackground(new java.awt.Color(3, 4, 94));
        BtnBack.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        BtnBack.setForeground(new java.awt.Color(255, 255, 255));
        BtnBack.setText("←");
        BtnBack.setAlignmentY(0.0F);
        BtnBack.setBorder(null);
        BtnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnBack.setFocusPainted(false);
        BtnBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnBack.setInheritsPopupMenu(true);
        BtnBack.setMargin(new java.awt.Insets(2, 14, 0, 14));
        BtnBack.setMaximumSize(new java.awt.Dimension(32, 64));
        BtnBack.setPreferredSize(new java.awt.Dimension(60, 10));
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });
        PnlFooter.add(BtnBack, java.awt.BorderLayout.WEST);

        getContentPane().add(PnlFooter, java.awt.BorderLayout.SOUTH);

        PnlContenido.setBackground(new java.awt.Color(255, 255, 255));
        PnlContenido.setLayout(new java.awt.GridBagLayout());

        SPVentas.setPreferredSize(new java.awt.Dimension(1000, 500));

        TblVentas.setBackground(new java.awt.Color(255, 255, 255));
        TblVentas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TblVentas.setForeground(new java.awt.Color(0, 0, 0));
        TblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Taco",  new Integer(1),  new Float(200.5),  new Float(200.5)}
            },
            new String [] {
                "Producto", "Cantidad", "Precio Unitario", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblVentas.setGridColor(new java.awt.Color(153, 153, 153));
        TblVentas.setPreferredSize(new java.awt.Dimension(1000, 80));
        TblVentas.setRowHeight(30);
        TblVentas.setShowGrid(false);
        TblVentas.setShowHorizontalLines(true);
        TblVentas.setShowVerticalLines(true);
        SPVentas.setViewportView(TblVentas);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        PnlContenido.add(SPVentas, gridBagConstraints);

        PnlDetalleVenta.setBackground(new java.awt.Color(255, 232, 236));
        PnlDetalleVenta.setForeground(new java.awt.Color(255, 204, 204));
        PnlDetalleVenta.setPreferredSize(new java.awt.Dimension(450, 200));
        PnlDetalleVenta.setLayout(new java.awt.GridBagLayout());

        LblFolio.setBackground(new java.awt.Color(0, 0, 0));
        LblFolio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblFolio.setForeground(new java.awt.Color(0, 0, 0));
        LblFolio.setText("Folio: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 0);
        PnlDetalleVenta.add(LblFolio, gridBagConstraints);

        LblFecha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblFecha.setForeground(new java.awt.Color(0, 0, 0));
        LblFecha.setText("Fecha: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 0);
        PnlDetalleVenta.add(LblFecha, gridBagConstraints);

        LblMetodo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblMetodo.setForeground(new java.awt.Color(0, 0, 0));
        LblMetodo.setText("Metodo: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        PnlDetalleVenta.add(LblMetodo, gridBagConstraints);

        LblEstado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblEstado.setForeground(new java.awt.Color(0, 0, 0));
        LblEstado.setText("Estado: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 15, 0);
        PnlDetalleVenta.add(LblEstado, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        PnlContenido.add(PnlDetalleVenta, gridBagConstraints);

        LblTotoal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblTotoal.setForeground(new java.awt.Color(0, 0, 0));
        LblTotoal.setText("Total: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 100);
        PnlContenido.add(LblTotoal, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(228, 37, 37));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cerrar");
        jButton1.setBorder(null);
        jButton1.setPreferredSize(new java.awt.Dimension(175, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        PnlContenido.add(jButton1, gridBagConstraints);

        getContentPane().add(PnlContenido, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GestionarVentaFrm gvf = new GestionarVentaFrm();
        gvf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(DetalleVentaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(DetalleVentaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(DetalleVentaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(DetalleVentaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalleVentaFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JLabel LblEstado;
    private javax.swing.JLabel LblFecha;
    private javax.swing.JLabel LblFolio;
    private javax.swing.JLabel LblMetodo;
    private javax.swing.JLabel LblTotoal;
    private javax.swing.JPanel PnlContenido;
    private javax.swing.JPanel PnlDetalleVenta;
    private javax.swing.JPanel PnlFooter;
    private javax.swing.JPanel PnlHeader;
    private javax.swing.JScrollPane SPVentas;
    private javax.swing.JTable TblVentas;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
