/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GestionarVentas;

import Componentes.TarjetaPago;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author rramirez
 */
public class MetodoEfectivoFrm extends javax.swing.JFrame {

    private Runnable onAceptar;
    
    /**
     * Creates new form MenuFrm
     * @param total
     */
    public MetodoEfectivoFrm(
            BigDecimal total,
            Runnable onAceptar
    ) {
        this.onAceptar = onAceptar;
        
        initComponents();
        setExtendedState(MetodoEfectivoFrm.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        
        LblTotalMonto.setText(total.toString());
        
        AbstractDocument doc = (AbstractDocument) TxtPago.getDocument();
        doc.setDocumentFilter(new DocumentFilter() {
            @Override
            public void insertString(FilterBypass fb, int offset, String string, AttributeSet attr) throws BadLocationException {
                if (string.matches("\\d+")) { // Solo números
                    super.insertString(fb, offset, string, attr);
                }
            }

            @Override
            public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                if (text != null && text.matches("\\d+")) { // Solo números
                    super.replace(fb, offset, length, text, attrs);
                }
            }
        });
        
        TxtPago.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) { calcularPago(); }
            @Override
            public void removeUpdate(DocumentEvent e) { calcularPago(); }
            @Override
            public void changedUpdate(DocumentEvent e) {}
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PnlHeader = new javax.swing.JPanel();
        PnlFooter = new javax.swing.JPanel();
        BtnBack = new javax.swing.JButton();
        PnlContenido = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblTotalEtiqueta = new javax.swing.JLabel();
        LblPagoEtiqueta = new javax.swing.JLabel();
        LblCambioEtiqueta = new javax.swing.JLabel();
        LblTotalMonto = new javax.swing.JLabel();
        TxtPago = new javax.swing.JTextField();
        LblCambioMonto = new javax.swing.JLabel();
        BtnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        PnlHeader.setBackground(new java.awt.Color(47, 102, 144));
        PnlHeader.setPreferredSize(new java.awt.Dimension(1024, 60));

        javax.swing.GroupLayout PnlHeaderLayout = new javax.swing.GroupLayout(PnlHeader);
        PnlHeader.setLayout(PnlHeaderLayout);
        PnlHeaderLayout.setHorizontalGroup(
            PnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PnlHeaderLayout.setVerticalGroup(
            PnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(PnlHeader, java.awt.BorderLayout.NORTH);

        PnlFooter.setBackground(new java.awt.Color(47, 102, 144));
        PnlFooter.setPreferredSize(new java.awt.Dimension(1024, 60));
        PnlFooter.setLayout(new java.awt.GridBagLayout());

        BtnBack.setBackground(new java.awt.Color(3, 4, 94));
        BtnBack.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        BtnBack.setForeground(new java.awt.Color(255, 255, 255));
        BtnBack.setText("←");
        BtnBack.setAlignmentY(0.0F);
        BtnBack.setBorder(null);
        BtnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnBack.setFocusPainted(false);
        BtnBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnBack.setInheritsPopupMenu(true);
        BtnBack.setMargin(new java.awt.Insets(2, 14, 0, 14));
        BtnBack.setMaximumSize(new java.awt.Dimension(32, 64));
        BtnBack.setPreferredSize(new java.awt.Dimension(60, 10));
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 2.0;
        PnlFooter.add(BtnBack, gridBagConstraints);

        getContentPane().add(PnlFooter, java.awt.BorderLayout.SOUTH);

        PnlContenido.setBackground(new java.awt.Color(255, 255, 255));
        PnlContenido.setLayout(new java.awt.GridBagLayout());

        LblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        LblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 80)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(3, 4, 94));
        LblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitulo.setText("Efectivo");
        LblTitulo.setAlignmentY(0.0F);
        LblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.weighty = 1.0;
        PnlContenido.add(LblTitulo, gridBagConstraints);

        LblTotalEtiqueta.setBackground(new java.awt.Color(255, 255, 255));
        LblTotalEtiqueta.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LblTotalEtiqueta.setForeground(new java.awt.Color(3, 4, 94));
        LblTotalEtiqueta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTotalEtiqueta.setText("Total: ");
        LblTotalEtiqueta.setAlignmentY(0.0F);
        LblTotalEtiqueta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LblTotalEtiqueta.setPreferredSize(new java.awt.Dimension(100, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        PnlContenido.add(LblTotalEtiqueta, gridBagConstraints);

        LblPagoEtiqueta.setBackground(new java.awt.Color(255, 255, 255));
        LblPagoEtiqueta.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LblPagoEtiqueta.setForeground(new java.awt.Color(3, 4, 94));
        LblPagoEtiqueta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblPagoEtiqueta.setText("Pago: ");
        LblPagoEtiqueta.setAlignmentY(0.0F);
        LblPagoEtiqueta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LblPagoEtiqueta.setPreferredSize(new java.awt.Dimension(100, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        PnlContenido.add(LblPagoEtiqueta, gridBagConstraints);

        LblCambioEtiqueta.setBackground(new java.awt.Color(255, 255, 255));
        LblCambioEtiqueta.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LblCambioEtiqueta.setForeground(new java.awt.Color(3, 4, 94));
        LblCambioEtiqueta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblCambioEtiqueta.setText("Cambio: ");
        LblCambioEtiqueta.setAlignmentY(0.0F);
        LblCambioEtiqueta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LblCambioEtiqueta.setPreferredSize(new java.awt.Dimension(150, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        PnlContenido.add(LblCambioEtiqueta, gridBagConstraints);

        LblTotalMonto.setBackground(new java.awt.Color(255, 255, 255));
        LblTotalMonto.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LblTotalMonto.setForeground(new java.awt.Color(3, 4, 94));
        LblTotalMonto.setText("100$");
        LblTotalMonto.setAlignmentY(0.0F);
        LblTotalMonto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LblTotalMonto.setPreferredSize(new java.awt.Dimension(100, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        PnlContenido.add(LblTotalMonto, gridBagConstraints);

        TxtPago.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        TxtPago.setForeground(new java.awt.Color(3, 4, 94));
        TxtPago.setText("0");
        TxtPago.setPreferredSize(new java.awt.Dimension(150, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        PnlContenido.add(TxtPago, gridBagConstraints);

        LblCambioMonto.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LblCambioMonto.setForeground(new java.awt.Color(3, 4, 94));
        LblCambioMonto.setText("$");
        LblCambioMonto.setPreferredSize(new java.awt.Dimension(150, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        PnlContenido.add(LblCambioMonto, gridBagConstraints);

        BtnAceptar.setBackground(new java.awt.Color(0, 119, 182));
        BtnAceptar.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        BtnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAceptar.setText("Aceptar");
        BtnAceptar.setBorder(null);
        BtnAceptar.setPreferredSize(new java.awt.Dimension(230, 75));
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 40, 0);
        PnlContenido.add(BtnAceptar, gridBagConstraints);

        getContentPane().add(PnlContenido, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        onAceptar.run();
    }//GEN-LAST:event_BtnAceptarActionPerformed

    private void calcularPago() {
        if (TxtPago.getText().isEmpty()) {
            return;
        }
        double total = Double.parseDouble(LblTotalMonto.getText());
        double efectivo = Double.parseDouble(TxtPago.getText());
        double cambio = efectivo - total;
        
        if (cambio < 0) {
            LblCambioMonto.setText("");
            return;
        }
        
        LblCambioMonto.setText(String.valueOf(cambio));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MetodoEfectivoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MetodoEfectivoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MetodoEfectivoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MetodoEfectivoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MetodoEfectivoFrm(BigDecimal.ZERO, () -> {}).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnBack;
    private javax.swing.JLabel LblCambioEtiqueta;
    private javax.swing.JLabel LblCambioMonto;
    private javax.swing.JLabel LblPagoEtiqueta;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel LblTotalEtiqueta;
    private javax.swing.JLabel LblTotalMonto;
    private javax.swing.JPanel PnlContenido;
    private javax.swing.JPanel PnlFooter;
    private javax.swing.JPanel PnlHeader;
    private javax.swing.JTextField TxtPago;
    // End of variables declaration//GEN-END:variables
}
