/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GestionarVentas;

import Componentes.TarjetaCategoria;
import Componentes.TarjetaProducto;

/**
 *
 * @author rramirez
 */
public class PuntoVentaFrm extends javax.swing.JFrame {

    /**
     * Creates new form MenuFrm
     */
    public PuntoVentaFrm() {
        initComponents();
        setExtendedState(PuntoVentaFrm.MAXIMIZED_BOTH);
        configurarCategorias();
        configurarCatalogo();
    }

    public void configurarCategorias() {
        PnlCategorias.setOpaque(false);
        PnlCategorias.setPreferredSize(new java.awt.Dimension(0, 150));

        PnlCategorias.setBorder(new javax.swing.border.EmptyBorder(0, 0, 20, 0));

        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.fill = java.awt.GridBagConstraints.BOTH;
        gbc.weighty = 1.0;

        // T1: CALDOS Y PLATOS
        gbc.weightx = 0.40;
        gbc.insets = new java.awt.Insets(0, 0, 0, 20);
        PnlCategorias.add(new TarjetaCategoria("CALDOS Y PLATOS", "9", new java.awt.Color(255, 51, 51)), gbc);

        // T2: TACOS
        gbc.weightx = 0.20;
        gbc.insets = new java.awt.Insets(0, 0, 0, 20);
        PnlCategorias.add(new TarjetaCategoria("TACOS", "8", new java.awt.Color(255, 128, 0)), gbc);

        // T3: COMBOS
        gbc.weightx = 0.20;
        gbc.insets = new java.awt.Insets(0, 0, 0, 20);
        PnlCategorias.add(new TarjetaCategoria("COMBOS", "1", new java.awt.Color(156, 39, 176)), gbc);

        // T4: BEBIDAS
        gbc.weightx = 0.20;
        gbc.insets = new java.awt.Insets(0, 0, 0, 0);
        PnlCategorias.add(new TarjetaCategoria("BEBIDAS", "4", new java.awt.Color(0, 51, 255)), gbc);

        PnlCategorias.revalidate();
        PnlCategorias.repaint();
    }

    public void configurarCatalogo() {

        ScrollCatalogo.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        ScrollCatalogo.setOpaque(false);
        ScrollCatalogo.getViewport().setOpaque(false);

        ScrollCatalogo.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        ScrollCatalogo.getVerticalScrollBar().setUnitIncrement(16);


        PnlCatalogo.setOpaque(false);
        PnlCatalogo.removeAll();

        PnlCatalogo.setLayout(new java.awt.GridLayout(0, 3, 20, 20));

        // Dummys hacer un llenarCatalogo()
        PnlCatalogo.add(new TarjetaProducto("Taco de Cahuamanta", 35.0, "TacoCahuamanta.png"));
        PnlCatalogo.add(new TarjetaProducto("Taco de Cahuamanta con Camarón", 50.0, "TacoCahuamanta.png"));
        PnlCatalogo.add(new TarjetaProducto("Taco de Moronga", 35.0, "TacoCahuamanta.png"));
        PnlCatalogo.add(new TarjetaProducto("Taco de Aleta", 90.0, "TacoCahuamanta.png"));
        PnlCatalogo.add(new TarjetaProducto("Taco de Camarón Empanizado", 55.0, "TacoCahuamanta.png"));
        PnlCatalogo.add(new TarjetaProducto("Taco de Camarón Cocido", 80.0, "TacoCahuamanta.png"));
        PnlCatalogo.add(new TarjetaProducto("Taco de Aleta y Camarón", 110.0, "TacoCahuamanta.png"));
        PnlCatalogo.add(new TarjetaProducto("Taco de Pescado Frito", 50.0, "TacoCahuamanta.png"));

        javax.swing.JPanel wrapper = new javax.swing.JPanel(new java.awt.BorderLayout());
        wrapper.setOpaque(false);
        wrapper.add(PnlCatalogo, java.awt.BorderLayout.NORTH);

        ScrollCatalogo.setViewportView(wrapper);

        ScrollCatalogo.revalidate();
        ScrollCatalogo.repaint();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PnlContenido = new javax.swing.JPanel();
        PnlIzquierdo = new javax.swing.JPanel();
        PnlCategorias = new javax.swing.JPanel();
        ScrollCatalogo = new javax.swing.JScrollPane();
        PnlWrraper = new javax.swing.JPanel();
        PnlCatalogo = new javax.swing.JPanel();
        PnlResumen = new javax.swing.JPanel();
        PnlCardSeleccionado = new javax.swing.JPanel();
        LblnombreProducto = new javax.swing.JLabel();
        LblCantidad = new javax.swing.JLabel();
        BoxCantidad = new javax.swing.JSpinner();
        BtnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        PnlContenido.setBackground(new java.awt.Color(252, 252, 252));
        PnlContenido.setForeground(new java.awt.Color(255, 255, 255));
        PnlContenido.setLayout(new java.awt.GridBagLayout());

        PnlIzquierdo.setBackground(new java.awt.Color(204, 204, 204));
        PnlIzquierdo.setOpaque(false);
        PnlIzquierdo.setLayout(new java.awt.BorderLayout());

        PnlCategorias.setLayout(new java.awt.GridBagLayout());
        PnlIzquierdo.add(PnlCategorias, java.awt.BorderLayout.NORTH);

        ScrollCatalogo.setBorder(null);

        PnlWrraper.setLayout(new java.awt.BorderLayout());

        PnlCatalogo.setLayout(new java.awt.GridLayout());
        PnlWrraper.add(PnlCatalogo, java.awt.BorderLayout.NORTH);

        ScrollCatalogo.setViewportView(PnlWrraper);

        PnlIzquierdo.add(ScrollCatalogo, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 10);
        PnlContenido.add(PnlIzquierdo, gridBagConstraints);

        PnlResumen.setBackground(new java.awt.Color(255, 255, 255));
        PnlResumen.setLayout(new java.awt.GridBagLayout());

        PnlCardSeleccionado.setLayout(new java.awt.GridBagLayout());
        PnlResumen.add(PnlCardSeleccionado, new java.awt.GridBagConstraints());

        LblnombreProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblnombreProducto.setForeground(new java.awt.Color(0, 0, 0));
        LblnombreProducto.setText("Taco de Cahuamanta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 5, 10);
        PnlResumen.add(LblnombreProducto, gridBagConstraints);

        LblCantidad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblCantidad.setForeground(new java.awt.Color(0, 0, 0));
        LblCantidad.setText("Cantidad: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 5);
        PnlResumen.add(LblCantidad, gridBagConstraints);

        BoxCantidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BoxCantidad.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 15, 10);
        PnlResumen.add(BoxCantidad, gridBagConstraints);

        BtnAgregar.setBackground(new java.awt.Color(0, 17, 255));
        BtnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregar.setText("Argegar");
        BtnAgregar.setBorder(null);
        BtnAgregar.setPreferredSize(new java.awt.Dimension(100, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 15);
        PnlResumen.add(BtnAgregar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 20, 20);
        PnlContenido.add(PnlResumen, gridBagConstraints);

        getContentPane().add(PnlContenido, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(PuntoVentaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(PuntoVentaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(PuntoVentaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(PuntoVentaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PuntoVentaFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner BoxCantidad;
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JLabel LblCantidad;
    private javax.swing.JLabel LblnombreProducto;
    private javax.swing.JPanel PnlCardSeleccionado;
    private javax.swing.JPanel PnlCatalogo;
    private javax.swing.JPanel PnlCategorias;
    private javax.swing.JPanel PnlContenido;
    private javax.swing.JPanel PnlIzquierdo;
    private javax.swing.JPanel PnlResumen;
    private javax.swing.JPanel PnlWrraper;
    private javax.swing.JScrollPane ScrollCatalogo;
    // End of variables declaration//GEN-END:variables
}
