/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GestionarVentas;

import Componentes.TarjetaPago;
import java.awt.GridBagConstraints;
import java.awt.Insets;

/**
 *
 * @author rramirez
 */
public class ResumenVentaFrm extends javax.swing.JFrame {

    /**
     * Creates new form MenuFrm
     */
    public ResumenVentaFrm() {
        initComponents();
        setExtendedState(ResumenVentaFrm.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        aplicarEstilosResumenVenta();

    }

    private void aplicarEstilosResumenVenta() {
        ScrollListaProductos.setBorder(null);
        ScrollListaProductos.setViewportBorder(null);
        ScrollListaProductos.setBackground(java.awt.Color.WHITE);
        ScrollListaProductos.getViewport().setBackground(java.awt.Color.WHITE);

        TblListaProductos.setBackground(java.awt.Color.WHITE);
        TblListaProductos.setShowGrid(false);
        TblListaProductos.setRowHeight(35);

        javax.swing.table.DefaultTableCellRenderer alignRight = new javax.swing.table.DefaultTableCellRenderer();
        alignRight.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        alignRight.setBackground(java.awt.Color.WHITE); // Evita que se ponga gris
        TblListaProductos.getColumnModel().getColumn(1).setCellRenderer(alignRight);

        PnlAgrupadorTotal.setOpaque(false);

        //Btn
        BtnAceptar.setForeground(java.awt.Color.WHITE);
        BtnAceptar.setFocusPainted(false);
        BtnAceptar.setPreferredSize(new java.awt.Dimension(220, 55));
        BtnAceptar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        BtnAceptar.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 10, 15));
        java.awt.Dimension dimensionBoton = new java.awt.Dimension(220, 75);
        BtnAceptar.setMinimumSize(dimensionBoton);
        BtnAceptar.setMaximumSize(dimensionBoton);
        BtnAceptar.setPreferredSize(dimensionBoton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PnlHeader = new javax.swing.JPanel();
        PnlFooter = new javax.swing.JPanel();
        BtnBack = new javax.swing.JButton();
        PnlContenido = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblHeaderProductos = new javax.swing.JLabel();
        LblHeaderSubtotal = new javax.swing.JLabel();
        ScrollListaProductos = new javax.swing.JScrollPane();
        TblListaProductos = new javax.swing.JTable();
        TblListaProductos.setTableHeader(null);
        PnlAgrupadorTotal = new javax.swing.JPanel();
        LblTotalEtiqueta = new javax.swing.JLabel();
        LblTotalMonto = new javax.swing.JLabel();
        BtnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        PnlHeader.setBackground(new java.awt.Color(47, 102, 144));
        PnlHeader.setPreferredSize(new java.awt.Dimension(1024, 60));

        javax.swing.GroupLayout PnlHeaderLayout = new javax.swing.GroupLayout(PnlHeader);
        PnlHeader.setLayout(PnlHeaderLayout);
        PnlHeaderLayout.setHorizontalGroup(
            PnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PnlHeaderLayout.setVerticalGroup(
            PnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(PnlHeader, java.awt.BorderLayout.NORTH);

        PnlFooter.setBackground(new java.awt.Color(47, 102, 144));
        PnlFooter.setPreferredSize(new java.awt.Dimension(1024, 60));
        PnlFooter.setLayout(new java.awt.GridBagLayout());

        BtnBack.setBackground(new java.awt.Color(3, 4, 94));
        BtnBack.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        BtnBack.setForeground(new java.awt.Color(255, 255, 255));
        BtnBack.setText("←");
        BtnBack.setAlignmentY(0.0F);
        BtnBack.setBorder(null);
        BtnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnBack.setFocusPainted(false);
        BtnBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnBack.setInheritsPopupMenu(true);
        BtnBack.setMargin(new java.awt.Insets(2, 14, 0, 14));
        BtnBack.setMaximumSize(new java.awt.Dimension(32, 64));
        BtnBack.setPreferredSize(new java.awt.Dimension(60, 10));
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 2.0;
        PnlFooter.add(BtnBack, gridBagConstraints);

        getContentPane().add(PnlFooter, java.awt.BorderLayout.SOUTH);

        PnlContenido.setBackground(new java.awt.Color(255, 255, 255));
        PnlContenido.setLayout(new java.awt.GridBagLayout());

        LblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        LblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 80)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(3, 4, 94));
        LblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitulo.setText("Resumen de Venta");
        LblTitulo.setAlignmentY(0.0F);
        LblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 40, 0);
        PnlContenido.add(LblTitulo, gridBagConstraints);

        LblHeaderProductos.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LblHeaderProductos.setForeground(new java.awt.Color(3, 4, 94));
        LblHeaderProductos.setText("Productos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 400, 10, 0);
        PnlContenido.add(LblHeaderProductos, gridBagConstraints);

        LblHeaderSubtotal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LblHeaderSubtotal.setForeground(new java.awt.Color(3, 4, 94));
        LblHeaderSubtotal.setText("Subtotal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 400);
        PnlContenido.add(LblHeaderSubtotal, gridBagConstraints);

        ScrollListaProductos.setBorder(null);
        ScrollListaProductos.setForeground(new java.awt.Color(229, 229, 229));

        TblListaProductos.setBackground(new java.awt.Color(229, 229, 229));
        TblListaProductos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TblListaProductos.setForeground(new java.awt.Color(0, 0, 0));
        TblListaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Taco de Cahuamanta", "$35"},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Producto", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollListaProductos.setViewportView(TblListaProductos);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 400, 10, 400);
        PnlContenido.add(ScrollListaProductos, gridBagConstraints);

        PnlAgrupadorTotal.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        LblTotalEtiqueta.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LblTotalEtiqueta.setForeground(new java.awt.Color(3, 4, 94));
        LblTotalEtiqueta.setText("Total: ");
        PnlAgrupadorTotal.add(LblTotalEtiqueta);

        LblTotalMonto.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        LblTotalMonto.setForeground(new java.awt.Color(3, 4, 94));
        LblTotalMonto.setText("$35");
        PnlAgrupadorTotal.add(LblTotalMonto);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 40, 400);
        PnlContenido.add(PnlAgrupadorTotal, gridBagConstraints);

        BtnAceptar.setBackground(new java.awt.Color(0, 119, 182));
        BtnAceptar.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        BtnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAceptar.setText("Aceptar");
        BtnAceptar.setBorder(null);
        BtnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAceptar.setPreferredSize(new java.awt.Dimension(230, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 40, 0);
        PnlContenido.add(BtnAceptar, gridBagConstraints);

        getContentPane().add(PnlContenido, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ResumenVentaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ResumenVentaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ResumenVentaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ResumenVentaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResumenVentaFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnBack;
    private javax.swing.JLabel LblHeaderProductos;
    private javax.swing.JLabel LblHeaderSubtotal;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel LblTotalEtiqueta;
    private javax.swing.JLabel LblTotalMonto;
    private javax.swing.JPanel PnlAgrupadorTotal;
    private javax.swing.JPanel PnlContenido;
    private javax.swing.JPanel PnlFooter;
    private javax.swing.JPanel PnlHeader;
    private javax.swing.JScrollPane ScrollListaProductos;
    private javax.swing.JTable TblListaProductos;
    // End of variables declaration//GEN-END:variables
}
